---
production: &default
  port: 3000
  db:
    host: 'localhost'
    port: 27017
    db_name: 'test'
    user: 'appUser'
    password: 'xyz123'
  secretCookies: '6777CD62A3E97C837CAF58BCC2AEC'
  secretToken: '6777CD62A3E97C837CAF58BCC2AEC'
  html:
    livereload: false

test: &test
  <<: *default

development: &development
  <<: *default
  db:
    host: 'localhost'
    port: 27017
    db_name: 'test'
    user: false
    password: false
  html:
    livereload: true
...
